### ISSUE TITLE
v1.0.0-alpha.0 release checklist

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#305]
- [x] Update Readme.md;
- [x] Update Kubernetes, containerd, cri-tools to newest tagged release;
- [x] Create `cri-containerd-release` bucket, and publish release tarball;
- [x] Update ansible playbook to point to the official release;
- [x] Release note.

**Comment by crosbymichael** [comment]
If you need help with any releases, getting runc binaries, etc let me know.

**Comment by Random-Liu** [comment]
@crosbymichael Thanks! :)

**Comment by Random-Liu** [comment]
Close since all are done.
