### ISSUE TITLE
CRI-Containerd Missing Pieces

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes-incubator/cri-containerd#62]
`cri-containerd` already supports basic container/sandbox lifecycle and image management today. However, there are still many missing pieces. List them here with relative proprieties:

## Missing Features
- [x] [P0] **Privileged support.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/29, PR: https://github.com/kubernetes-incubator/cri-containerd/pull/51)
- [x] [P0] **Stop container with image default stop signal.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/61, PR: #83)
- [x] [P1] **Container logging.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/56)
- [x] [P1] **ExecSync.** `ExecSync` is very useful for testing, so prioritize it.
- [x] [P1] **Pull image authentication.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/58, PR: #88)
- [x] [P1] **Sandbox `/etc/resolv.conf`.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/28, PR: https://github.com/kubernetes-incubator/cri-containerd/pull/50)
- [x] [P1] **Sandbox `/etc/hosts`.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/60)
- [x] [P1] **Sandbox `/dev/shm`.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/67)
- [x] [P1] **Device mapping.** (PR: #51)
- [x] [P1] **Set user/username.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/146, https://github.com/kubernetes-incubator/cri-containerd/pull/168)
- [x] [P1] **ExecSync timeout.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/137)
- [x] [P2] **Selinux options/label.** (PR: #157)
- [x] [P2] **Container streaming.**
  - [x] Exec (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/115)
  - [x] Attach
  - [x] Portforward (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/130)
- [x] [P2] **Support systemd cgroup.** (PR: #290)
- [ ] [P3] **Image list filter.**
- [x] [P2] **CRI conformance.** Stop running container when stopping sandbox, remove container when removing sandbox etc. (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/77)
- [x] [P2] **OOM Event.** Handle containerd event, and set container status exit reason correspondingly. (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/91)
- [x] [P2] **Apparmor**. (PR: #159)
- [x] [P2] **Seccomp**. (PR: #219)
- [x] [P2] **Sysctl** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/119).
- [x] [P2] **Other pod sandbox security context (user/selinux etc.).** Figure out what this means to sandbox container.
- [x] [P2] **Container metrics.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/265)
- [x] [P2] **Image filesystem metrics.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/257)
- [x] [P2] **Container manager.** Add container manager to ensure `containerd` and cri-containerd are in runtime cgroup. (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/181, PR: https://github.com/containerd/containerd/pull/1443, https://github.com/kubernetes-incubator/cri-containerd/pull/184)
- [x] [P2] **Host port. (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/154)**

## Improvements
- [x] [P0] **Switch to containerd api.** Including change the implementation and update unit test (add mock client etc.). (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/49)
- [x] [P1] **Switch to new containerd client.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/113)
- [x] [P1] **Refactor metadata store.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/66)
  * Add pure in-memory cache for image management;
  * Add in-memory wrapper for sandbox/container metadata store, because there are several things which don't need to be checkpointed.
  * Reconsider what we should store in container labels.
- [x] [P1] **Create permanent network namespace.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/43, PR: https://github.com/kubernetes-incubator/cri-containerd/pull/54)
- [x] ~~[P2] **Add unit test for image.** With new containerd client, it's much easier to add unit test for image part. (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/36)~~
- [x] [P3] **Check image config and top level snapshot existence when list/Inspect image.** (Issue: https://github.com/containerd/containerd/issues/1514, https://github.com/kubernetes-incubator/cri-containerd/issues/303)
- [x] [P1] **Default sandbox container resource limit.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/92)
- [x] [P3] **Add truncindex for image and container id.** (PR: https://github.com/kubernetes-incubator/cri-containerd/pull/235)
- [ ] [P2] **Reliable containerd event handling.** Requeue event on error.
- [x] [P2] **Checkpoint versioning.** (Metadata and status are all versioned now)
- [x] [P2] **Handle recovery from `cri-containerd` and `containerd` restart.**

## Containerd Missing Features
- [x] [P0] **V2 Schema 1 image support.** (Issue: https://github.com/kubernetes-incubator/cri-containerd/issues/35, https://github.com/containerd/containerd/issues/851)
- [x] [P1] **Image (content/snapshot) garbage collection.**
- [x] ~~[P1] **Containerd version.** Containerd doesn't report semver because of a bug.~~

**Comment by stevvooe** [comment]
> Containerd doesn't report semver because of a bug.

We just haven't tagged a revision yet. The version field will contain the proper git tag, which will be semantic versioned. If the release is made off an untagged revision, it will be qualified with git commit, per `git describe`.

In general, I wouldn't recommend pushing down semantic versioning requirements on the runtimes.

**Comment by Random-Liu** [comment]
> We just haven't tagged a revision yet. The version field will contain the proper git tag, which will be semantic versioned.

Yeah, checked the code. That's the "bug" I mean. :)

> If the release is made off an untagged revision, it will be qualified with git commit, per git describe.

Hm, I checked Kubelet code, and it seems that we don't actually require it to be a semver. Although semver is better.

**Comment by mikebrow** [comment]
checked off seccomp..

**Comment by Random-Liu** [comment]
Most important features in this list are done. Move rest of stuff to next release.

**Comment by Random-Liu** [comment]
Filed #433 and #434 for the last 2 items. Close this one.
